# softmax_classifer 클래스를 이용하여 학습하기 
* 기존에 사용하던 내용을 클래스로 모아서 처리한다. 

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
class softmax_classifer(tf.keras.Model):
    
    def __init__(self, nb_classes):
        super(softmax_classifer, self).__init__()
        self.W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
        self.b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
        self.vars = [self.W, self.b]
        print(self.W.shape)
        
    def softmax_regression(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)
    
    def cost_fn(self, X, Y):
        logits = self.softmax_regression(X)  # x에 대한 가설값 
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis=1))  # 각 행에 대해 비용을 구한 후 함계 반환 -> 평균 
        return cost
    
    def grad_fn(self, X, Y):
        with tf.GradientTape() as tape:
            cost = self.cost_fn(X, Y)
            grads = tape.gradient(cost, self.vars)            # [W, b]
            return grads
        
    def fit(self, X, Y, epochs=2000, verbose=100):
        optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

        for i in range(epochs):
            grads = self.grad_fn(X, Y)
            optimizer.apply_gradients(zip(grads, self.vars))  # [W, b]
            if (i==0) | ((i+1)%verbose==0):
                print('Loss at epoch %d: %f' %(i+1, self.cost_fn(X, Y).numpy()))

In [3]:
# 1 데이터 
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

# one-hot encoding
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

In [4]:
model = softmax_classifer(nb_classes)

(4, 3)


In [5]:
model.softmax_regression(x_data)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[6.1106874e-04, 5.0358929e-02, 9.4902998e-01],
       [4.1489478e-05, 2.9441500e-02, 9.7051710e-01],
       [3.1519960e-06, 2.7947465e-03, 9.9720216e-01],
       [1.9422943e-08, 4.7825437e-04, 9.9952173e-01],
       [1.3190551e-13, 5.9269351e-10, 1.0000000e+00],
       [7.8297093e-09, 2.6317453e-08, 1.0000000e+00],
       [1.0550820e-13, 9.2418455e-11, 1.0000000e+00],
       [7.2360251e-16, 1.2852279e-12, 1.0000000e+00]], dtype=float32)>

In [6]:
model.cost_fn(x_data, y_data)

<tf.Tensor: shape=(), dtype=float32, numpy=13.896508>

In [7]:
model.grad_fn(x_data, y_data)

ListWrapper([<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.24991205, -0.7350576 ,  0.9849697 ],
       [-1.6248417 , -1.233321  ,  2.8581626 ],
       [-1.6249068 , -1.8563176 ,  3.4812245 ],
       [-1.6249115 , -1.9846485 ,  3.6095603 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.24991803, -0.36461583,  0.6145339 ], dtype=float32)>])

In [8]:
model.fit(x_data, y_data)

Loss at epoch 1: 8.846265
Loss at epoch 100: 0.688531
Loss at epoch 200: 0.590216
Loss at epoch 300: 0.533905
Loss at epoch 400: 0.488768
Loss at epoch 500: 0.448979
Loss at epoch 600: 0.412208
Loss at epoch 700: 0.377038
Loss at epoch 800: 0.342338
Loss at epoch 900: 0.307141
Loss at epoch 1000: 0.271166
Loss at epoch 1100: 0.241261
Loss at epoch 1200: 0.228160
Loss at epoch 1300: 0.217385
Loss at epoch 1400: 0.207537
Loss at epoch 1500: 0.198504
Loss at epoch 1600: 0.190189
Loss at epoch 1700: 0.182513
Loss at epoch 1800: 0.175406
Loss at epoch 1900: 0.168809
Loss at epoch 2000: 0.162670
