# softmax_classifer 클래스를 이용하여 학습하기 
* 기존에 사용하던 내용을 클래스로 모아서 처리한다. 

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
class softmax_classifer(tf.keras.Model):
    
    def __init__(self, nb_classes):
        super(softmax_classifer, self).__init__()
        self.W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
        self.b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
        self.var = [self.W, self.b]
        print(self.W.shape)
        
    def softmax_regression(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)
    
    def cost_fn(self, X, Y):
        logits = self.softmax_regression(X)  # x에 대한 가설값 
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis=1))  # 각 행에 대해 비용을 구한 후 함계 반환 -> 평균 
        return cost
    
    def grad_fn(self, X, Y):
        with tf.GradientTape() as tape:
            cost = self.cost_fn(X, Y)
            grads = tape.gradient(cost, self.var)            
            return grads
        
    def fit(self, X, Y, epochs=2000, verbose=100):
        optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

        for i in range(epochs):
            grads = self.grad_fn(X, Y)
            optimizer.apply_gradients(zip(grads, self.var))
            if (i==0) | ((i+1)%verbose==0):
                print('Loss at epoch %d: %f' %(i+1, self.cost_fn(X, Y).numpy()))

In [3]:
# 1 데이터 
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

# one-hot encoding
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

In [4]:
model = softmax_classifer(nb_classes)

(4, 3)


In [5]:
model.softmax_regression(x_data)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[4.6104848e-01, 2.8236478e-03, 5.3612787e-01],
       [9.8282880e-01, 1.7377192e-03, 1.5433442e-02],
       [9.9955648e-01, 2.6865685e-04, 1.7482902e-04],
       [9.9995792e-01, 2.9699895e-05, 1.2454701e-05],
       [5.8755869e-01, 5.8864766e-09, 4.1244128e-01],
       [9.9997830e-01, 3.2764964e-07, 2.1332591e-05],
       [9.8552924e-01, 3.0639584e-09, 1.4470778e-02],
       [9.9153143e-01, 1.4015847e-10, 8.4684817e-03]], dtype=float32)>

In [6]:
model.cost_fn(x_data, y_data)

<tf.Tensor: shape=(), dtype=float32, numpy=7.2219605>

In [7]:
model.grad_fn(x_data, y_data)

ListWrapper([<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.3737255 , -0.74909693, -0.62462866],
       [ 1.2339004 , -1.2490395 ,  0.015139  ],
       [ 2.3999467 , -1.8738759 , -0.5260709 ],
       [ 2.527035  , -1.9990594 , -0.5279756 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.6259987 , -0.3743925 , -0.25160623], dtype=float32)>])

In [8]:
model.fit(x_data, y_data)

Loss at epoch 1: 5.001781
Loss at epoch 100: 0.726391
Loss at epoch 200: 0.652538
Loss at epoch 300: 0.598256
Loss at epoch 400: 0.549861
Loss at epoch 500: 0.503884
Loss at epoch 600: 0.458934
Loss at epoch 700: 0.414318
Loss at epoch 800: 0.369649
Loss at epoch 900: 0.324814
Loss at epoch 1000: 0.280519
Loss at epoch 1100: 0.243080
Loss at epoch 1200: 0.227534
Loss at epoch 1300: 0.216782
Loss at epoch 1400: 0.206956
Loss at epoch 1500: 0.197942
Loss at epoch 1600: 0.189645
Loss at epoch 1700: 0.181987
Loss at epoch 1800: 0.174896
Loss at epoch 1900: 0.168315
Loss at epoch 2000: 0.162191
