# 데이터 자르기 

## 1. split 함수 만들기(다 : 1 )

In [1]:
import numpy as np

In [2]:
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

#### 데이터 셋을 tims_steps만큼 나누는 함수 
* 연속된 데이터셋을 자르기 위해 만든 함수

In [3]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) - 1:
            break;
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [4]:
x, y = split_xy1(dataset, 4)
print(x, "\n", y)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]


####  RNN의 input_shape - 아래는 모두 같은 표현 
* (행, 열, 특성)
* (행, 열, 피쳐)
* (전체 샘플수, 타임스탭, 피처)
* (행, 열, 몇 개씩 자르는지)

## 2. split 함수 만들기(다 : 다 )

#### 데이터가 연결된 데이터를 자르는 함수 
* 주식, 환율, 물가, 선물, 파생상품 등의 경우에 사용가능 
* 시계열 데이터의 y 값은 애매하기 때문에 보통 데이터 분석가나 개발자의 몫

In [5]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break;
        tmp_x = dataset[i:x_end_number]
        tmp_y = dataset[x_end_number:y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [6]:
time_steps = 4
y_column = 2
x, y = split_xy2(dataset, time_steps, y_column)
print(x, "\n", y)
print("x.shape : ", x.shape)
print("y.shape : ", y.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
x.shape :  (5, 4)
y.shape :  (5, 2)


## 3. split 함수 만들기(다입력, 다 : 1 )
* 2차원 이상의 데이터를 입력받아 x는 다차원 배열로 나누고, y는 벡터 형태로 나누는 함수 작성 
* 데이터 셋은 10행 3열의 구조  

In [7]:
dataset2 = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset2.shape : ", dataset2.shape)
dataset2 = np.transpose(dataset2)
print(dataset2)
print("dataset.shape : ", dataset2.shape)

dataset2.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [8]:
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        
        if y_end_number > len(dataset):
            break;
        
        tmp_x = dataset[i:x_end_number, :-1]               # 정해진 범위의 행과 마지막 전까지 데이터 추출 
        tmp_y = dataset[x_end_number-1:y_end_number, -1]   # 정해진 범위의 마지막 행의 마지막 데이터 추출 
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [9]:
 x, y = split_xy3(dataset2, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(8, 3, 2)
(8, 1)


In [10]:
y = y.reshape(y.shape[0])
print(y.shape)

(8,)


## 4. split 함수 만들기(다입력, 다 : 다 )
* 2차원 이상의 데이터를 입력받아 x는 다차원 배열로 나누고, y는 벡터 형태로 나누는 함수 작성
* 데이터 셋은 10행 3열의 구조
* y_column 을 조절해서 처리 

In [11]:
x, y = x, y = split_xy3(dataset2, 3, 2) # 2를 1로 수정
print(x, "\n", y)
print(x.shape)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]] 
 [[23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]]
(7, 3, 2)


## 5. split 함수 만들기(다입력, 다 : 다 )2¶

In [12]:
def split_xy4(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        
        if y_end_number > len(dataset):
            break;
        
        tmp_x = dataset[i:x_end_number, :]               # 정해진 범위의 행의 데이터를 모두 추출 
        tmp_y = dataset[x_end_number:y_end_number,:]     # 정해진 범위의 마지막 행의 모든 데이터 추출 
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [13]:
x, y = split_xy4(dataset2, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
(7, 3, 3)
(7, 1, 3)
