In [2]:
import tensorflow as tf
tf.__version__

'2.1.0'

#### 난수 생성 

In [4]:
rand = tf.random.uniform([1], 0, 1)  # 균일 분포 
print(rand)

tf.Tensor([0.9439448], shape=(1,), dtype=float32)


In [6]:
rand = tf.random.uniform([4], 0, 10)
print(rand)

tf.Tensor([6.1027575 5.3365707 8.868741  7.528553 ], shape=(4,), dtype=float32)


In [7]:
rand = tf.random.normal([4], 0, 1)  # 정규 분포 
print(rand)

tf.Tensor([ 0.94358414 -1.4051745   0.29498348  0.518039  ], shape=(4,), dtype=float32)
