# 스칼라, 행렬, 텐서 연산 

In [1]:
import numpy as np

#### 1차원 행렬 만들기

In [6]:
vec1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(vec1)
print(vec1.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


#### 2차원 행렬 만들기 

In [7]:
mat1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(mat1)
print(mat1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [3]:
mat2 = np.matrix([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
mat2

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

#### 3차원 행렬 만들기

In [8]:
ten1 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(ten1)
print(ten1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


#### 행렬 덧셈

In [10]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat2 = np.matrix([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
mat3 = mat1 + mat2
print(mat3)

[[ 3  3  7]
 [ 8  6 13]
 [11 10 18]
 [15 32 13]]


In [11]:
mat4 = mat1 + 4
print(mat4)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
