# 행렬 곱셈

In [2]:
import numpy as np

In [3]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mat1)
print(mat1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [4]:
mat2 = np.array([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
print(mat2)
print(mat2.shape)

[[ 2  1  4]
 [ 4  1  7]
 [ 4  2  9]
 [ 5 21  1]]
(4, 3)


In [5]:
mat1.dot(mat2.T)

array([[ 16,  27,  35,  50],
       [ 37,  63,  80, 131],
       [ 58,  99, 125, 212],
       [ 79, 135, 170, 293]])

In [6]:
mat1.T.dot(mat2)

array([[ 96, 229, 105],
       [111, 254, 126],
       [126, 279, 147]])

In [7]:
np.reshape(mat1, [3,4]).dot(mat2)

array([[ 42,  93,  49],
       [102, 193, 133],
       [162, 293, 217]])

# 텐서 곱셈

In [9]:
ten1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(ten1)
print(ten1.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [10]:
ten2 = ten1.T
print(ten2)
print(ten2.shape)

[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]
(3, 2, 2)


In [13]:
ten3 = ten2.dot(ten1)
print(ten3)
print(ten3.shape)

[[[[ 5  7  9]
   [ 5  7  9]]

  [[20 28 36]
   [20 28 36]]]


 [[[10 14 18]
   [10 14 18]]

  [[25 35 45]
   [25 35 45]]]


 [[[15 21 27]
   [15 21 27]]

  [[30 42 54]
   [30 42 54]]]]
(3, 2, 2, 3)
