# 행렬 정형 및 전치

In [1]:
import numpy as np

In [2]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mat1)
print(mat1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [3]:
mat2 = np.reshape(mat1, [3,4])
print(mat2)
print(mat2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [4]:
mat3 = np.reshape(mat1, [3,2,2])
print(mat3)
print(mat3.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [6]:
mat4 = np.reshape(mat1, [12])
print(mat4)
print(mat4.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [7]:
mat5 = mat1.T  # 전치 
print(mat5)
print(mat5.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
(3, 4)


In [8]:
np.reshape(mat1, [3,4]) == mat1.T

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])