# 넘파이 설치와 활용

In [1]:
import numpy as np

#### 1. numpy 배열 생성하기 
* 0~14까지 15개의 숫자를 (3, 5)차원으로 생성 

In [2]:
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 2. 넘파이 배열 정보 확인 

In [3]:
arr1.shape

(3, 5)

In [4]:
arr1.dtype

dtype('int32')

#### 3. 다른 형태의 배열 생성하기 

In [5]:
arr2 = np.array([6, 7, 8])
print(arr2)

[6 7 8]


In [6]:
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 4. 넘파이 배열을 이용한 사칙연산 수행 

In [7]:
arr4 = np.array([
    [1,2,3],
    [4,5,6]
], dtype = np.float64)

arr5 = np.array([
    [7,8,9],
    [10,11,12]
], dtype = np.float64)

In [8]:
print("arr4 + arr5 = ")
print(arr4 + arr5,"\n")
print("arr4 - arr5 = ")
print(arr4 - arr5,"\n")
print("arr4 * arr5 = ")
print(arr4 * arr5,"\n")
print("arr4 / arr5 = ")
print(arr4 / arr5,"\n")

arr4 + arr5 = 
[[ 8. 10. 12.]
 [14. 16. 18.]] 

arr4 - arr5 = 
[[-6. -6. -6.]
 [-6. -6. -6.]] 

arr4 * arr5 = 
[[ 7. 16. 27.]
 [40. 55. 72.]] 

arr4 / arr5 = 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

