# 폴딩하지 않은 5개의 시쿼스 처리

In [1]:
import numpy as np 
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

2.1.0


#### 데이터 셋 준비 
* 원-핫 인코딩

In [3]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

#### Unfolding to n sequences
![Unfolding to n sequences](../imgs/unfolding_n_sequence.png)

####  하나의 RNN셀의 입력 차수(4) -> 출력 차수(2). 시퀀스 : 5

In [5]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)

hidden_size = 2

rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[-0.49528572  0.66285276]
  [-0.15525122 -0.3787176 ]
  [ 0.6214603  -0.82296324]
  [-0.16466856 -0.83746773]
  [-0.39773878 -0.4874155 ]]], shape: (1, 5, 2) 

states: [[-0.39773878 -0.4874155 ]], shape: (1, 2)


#### 하나의 RNN셀의 입력 차수(4) -> 출력 차수(2). 시퀀스 : 5, 배치 3

In [7]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2

rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.74553126  0.6438534 ]
  [ 0.69540524  0.50212955]
  [ 0.14907522 -0.03410923]
  [-0.35649675  0.48142436]
  [ 0.6687258  -0.489257  ]]

 [[ 0.19439693 -0.17596893]
  [ 0.13722315 -0.7895167 ]
  [-0.81025714  0.5040308 ]
  [ 0.185808    0.89978075]
  [ 0.50788987  0.43483973]]

 [[-0.32319725  0.5869868 ]
  [ 0.253652    0.75400263]
  [ 0.73734856 -0.4213858 ]
  [-0.23732962 -0.71868145]
  [-0.78104013  0.729404  ]]], shape: (3, 5, 2) 

states: [[ 0.6687258  -0.489257  ]
 [ 0.50788987  0.43483973]
 [-0.78104013  0.729404  ]], shape: (3, 2)


* outputs의 마지막 데이터와 states의 데이터가 동일