# Diabetes example

#### pip install scikit-learn 설치 필요

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split 
import numpy
numpy.random.seed(7)

Using TensorFlow backend.


In [2]:
dataset = numpy.loadtxt("diabetes.csv", delimiter=",")
X = dataset[:,:-1]
Y = dataset[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)  # 데이터를 나눠줌 
print(X_train, X_test, y_train, y_test)

[[-0.764706   0.175879   0.47541   ... -0.248882  -0.799317   0.       ]
 [-0.647059   0.396985  -0.114754  ... -0.23696   -0.723313  -0.966667 ]
 [ 0.294118   0.366834   0.377049  ... -0.156483  -0.844577  -0.3      ]
 ...
 [ 0.529412   0.0653266  0.147541  ...  0.0193741 -0.852263   0.0333333]
 [-0.764706  -0.165829   0.0819672 ... -0.0402384 -0.642186  -0.966667 ]
 [-0.764706  -0.145729   0.0655738 ...  0.180328  -0.272417  -0.8      ]] [[-0.647059  -0.175879   0.147541  ... -0.371088  -0.734415  -0.866667 ]
 [ 0.0588235  0.306533   0.147541  ...  0.0193741 -0.509821  -0.2      ]
 [-0.882353   0.226131   0.47541   ...  0.481371  -0.789069  -0.666667 ]
 ...
 [-0.176471   0.688442   0.442623  ...  0.138599  -0.394535  -0.366667 ]
 [ 0.529412   0.0452261  0.180328  ... -0.0700447 -0.669513  -0.433333 ]
 [ 0.         0.477387   0.393443  ...  0.275708  -0.746371  -0.9      ]] [1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0.

In [22]:
X_train.shape
X_train[0]

array([-0.764706,  0.175879,  0.47541 , -0.616162, -0.832151, -0.248882,
       -0.799317,  0.      ])

In [24]:
y_train.shape
y_train[1]

0.0

In [44]:
# 모델링 해보세요. 
# 3개층 

from keras import models
from keras import layers 

model = models.Sequential()
model.add(layers.Dense(12, activation='relu', input_shape=(8,)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [77]:
# 학습 시켜 보세요.
x_val = X_train[:100]
partial_x_train = X_train[100:]

y_val = y_train[:100]
partial_y_train = y_train[100:]
history = model.fit(X_train, y_train, epochs=10, batch_size=10, validation_data=(x_val, y_val))

Train on 508 samples, validate on 100 samples
Epoch 1/10
508/508 [==============================] - 0s 119us/step - loss: 0.3760 - accuracy: 0.8209 - val_loss: 0.3549 - val_accuracy: 0.8200
Epoch 2/10
508/508 [==============================] - 0s 108us/step - loss: 0.3734 - accuracy: 0.8031 - val_loss: 0.3586 - val_accuracy: 0.8300
Epoch 3/10
508/508 [==============================] - 0s 100us/step - loss: 0.3732 - accuracy: 0.8071 - val_loss: 0.3544 - val_accuracy: 0.8200
Epoch 4/10
508/508 [==============================] - 0s 102us/step - loss: 0.3714 - accuracy: 0.8150 - val_loss: 0.3513 - val_accuracy: 0.8400
Epoch 5/10
508/508 [==============================] - 0s 126us/step - loss: 0.3657 - accuracy: 0.8209 - val_loss: 0.3512 - val_accuracy: 0.8400
Epoch 6/10
508/508 [==============================] - 0s 102us/step - loss: 0.3731 - accuracy: 0.8209 - val_loss: 0.3616 - val_accuracy: 0.8500
Epoch 7/10
508/508 [==============================] - 0s 106us/step - loss: 0.3648 - accur

In [78]:
# model.evaluate(x값, y값) 함수를 사용하여 모델을 평가해보세요.

model.evaluate(X_test, y_test)



251/251 [==============================] - 0s 24us/step


[0.4882015222572236, 0.7848605513572693]

In [79]:
# model.predict(새로운 x값) 을 사용하여 예측해보세요.
aa = model.predict(X_test[0:5]) > 0.5  # 1이 일어날 확률 

aa = aa.astype('int')
aa

array([[1],
       [0],
       [1],
       [1],
       [0]])

In [76]:
bb = y_test[0:5]
bb = bb.astype('int')
bb

array([1, 0, 0, 1, 0])